Feature/implement job category
RUC-MSc-CS-CIT-2024/portfolio_subproject_2 pull request #50
Opened 2024-10-28 17:59 UTC by idax6797

> [!NOTE]  
> This PR experiences errors when building

This pull request introduces a new feature for managing job categories.
This includes a new controller, service, and repository for job categories.

### New Feature: Job Categories

* **JobCategoryController**: Added a new `JobCategoryController` class to handle API requests for job categories, including methods for pagination and HATEOAS links. (`src/CitMovie.Api/JobCategoryController.cs`)
* **JobCategoryService**: Introduced a `JobCategoryService` class to manage business logic for job categories. (`src/CitMovie.Business/JobCategoryService.cs`)
* **JobCategoryRepository**: Added a `JobCategoryRepository` and its interface to handle data access for job categories. (`src/CitMovie.Data/JobCategoryRepository/IJobCategoryRepository.cs`, `src/CitMovie.Data/JobCategoryRepository/JobCategoryRepository.cs`) [[1]](diffhunk://#diff-32436a6fcfbeccffa032188a4a7dc23676831d9eff5626cfc860cf50a0cc95e0R1-R10) [[2]](diffhunk://#diff-7a635da3bad3d4852adea6b30efcd243450667e1fc17185c28e0cc43d2d5e2f2R1-R33)
* **JobCategoryDto**: Created a `JobCategoryDto` class for data transfer objects related to job categories. (`src/CitMovie.Models/DTOs/JobCategoryDto.cs`)

2024-10-29 11:12 UTC, MarLaslo requested changes

2024-10-29 11:12 UTC, MarLaslo commented on src/CitMovie.Data/JobCategoryRepository/JobCategoryRepository.cs
> +        public async Task<IList<JobCategoryDto>> GetAllJobCategoriesAsync(int page, int pageSize)
To my understanding here we return the Domain object and not dto.  In the manager we do the conversion

2024-10-29 11:12 UTC, MarLaslo commented on src/CitMovie.Business/Managers/JobCategoryManager.cs
Also I think we should have an IJobCategoryManager interface as we have for all the other managers.

2024-10-29 17:49 UTC, MarLaslo approved these changes

2024-10-29 17:49 UTC, MarLaslo commented on src/CitMovie.Data/JobCategoryRepository/JobCategoryRepository.cs
> +                .Select(jc => new JobCategory
Also here not neccessary probably

2024-10-30 08:46 UTC, merged

2024-10-30 08:52 UTC, JuliusKryger requested changes

2024-10-30 08:52 UTC, JuliusKryger commented on src/CitMovie.Data/JobCategoryRepository/JobCategoryRepository.cs
> +            return await _context.JobCategories
Here kind of the same as last PR, we do not expect to update these only read them, so we can optimize this by letting EF know that with:

```suggestion
            return await _context.JobCategories
            .AsNoTracking()
```